import json
import os
from datetime import datetime
from compare import DeltaEngine

class ReportGenerator:
    def __init__(self, output_dir="reports"):
        self.output_dir = output_dir
        os.makedirs(self.output_dir, exist_ok=True)
        self.engine = DeltaEngine()

    def _format_delta(self, delta):
        if delta == "New":
            return "🆕 **New**"
        elif "↑" in delta:
            return f"🟢 {delta}"
        elif "↓" in delta:
            return f"🔴 {delta}"
        else:
            return "⚪ -"

    def generate(self):
        now = datetime.now()
        timestamp_str = now.strftime("%Y-%m-%d %H:%M:%S")
        filename = f"report_{now.strftime('%Y%m%d_%H%M%S')}.md"
        filepath = os.path.join(self.output_dir, filename)

        # Load Current Data
        or_data = []
        lmsys_data = []
        
        if os.path.exists("data/openrouter_current.json"):
            with open("data/openrouter_current.json", "r", encoding="utf-8") as f:
                or_data = json.load(f)
        
        if os.path.exists("data/lmsys_current.json"):
            with open("data/lmsys_current.json", "r", encoding="utf-8") as f:
                lmsys_data = json.load(f)

        # Get Deltas
        or_reports = self.engine.compare("openrouter", or_data)
        lmsys_reports = self.engine.compare("lmsys", lmsys_data)

        # Build Markdown
        md = f"""# 🤖 大模型今日趋势-{now.strftime('%m-%d')}

> 📅 **生成时间**: `{timestamp_str}`
> 📊 **数据源**: [OpenRouter Rankings](https://openrouter.ai/rankings) & [LMSYS Leaderboard](https://lmarena.ai/leaderboard)

---

## 🚀 OpenRouter 排行榜 (Top 10)
*基于 OpenRouter 平台真实部署与调用量统计*

| 排名 | 模型 ID | 使用量 (Tokens) | 增长率 | 变动 |
| :--- | :--- | :--- | :--- | :--- |
"""
        for item in or_reports[:10]:
            delta_styled = self._format_delta(item['delta'])
            # Extract new metrics from or_data corresponding to item
            curr_item = next((x for x in or_data if x['model_id'] == item['model_id']), {})
            tokens = curr_item.get('tokens', '-')
            growth = curr_item.get('growth', '-')
            md += f"| {item['rank']} | `{item['model_id']}` | {tokens} | {growth} | {delta_styled} | \n"

        md += f"""
---

## 🏆 LMSYS Chatbot Arena (Top 10)
*基于众测竞技场 Elo 分数统计*

| 排名 | 模型名称 | Elo 分数 | 投票数 | 变动 |
| :--- | :--- | :--- | :--- | :--- |
"""
        for item in lmsys_reports[:10]:
            delta_styled = self._format_delta(item['delta'])
            # Extract new metrics
            curr_item = next((x for x in lmsys_data if x['model_id'] == item['model_id']), {})
            votes = curr_item.get('votes', '-')
            md += f"| {item['rank']} | **{item['model_id']}** | {item['score']} | {votes} | {delta_styled} | \n"

        # Special Analysis Section
        md += "\n--- \n\n## 🔍 显著变动与新模型\n"
        
        new_models = [r['model_id'] for r in or_reports + lmsys_reports if r['delta'] == "New"]
        big_ups = [r['model_id'] for r in or_reports + lmsys_reports if "↑" in r['delta'] and int(r['delta'][1:]) >= 2]
        
        if new_models:
            md += "### 🆕 新上榜模型\n"
            for m in new_models[:5]:
                md += f"- `{m}`\n"
        
        if big_ups:
            md += "\n### 📈 表现强劲 (排名上升 >= 2)\n"
            for m in big_ups[:5]:
                md += f"- `{m}`\n"

        if not new_models and not big_ups:
            md += "本期排名相对稳定，未检测到显著异常变动。\n"

        md += "\n---\n*Report generated by LLM Trend Observer System*"

        with open(filepath, "w", encoding="utf-8") as f:
            f.write(md)
        
        # Also update a 'latest_report.md' for constants links
        with open(os.path.join(self.output_dir, "latest_report.md"), "w", encoding="utf-8") as f:
            f.write(md)

        print(f"Report generated: {filepath}")
        return filepath


